create table tbl_product (id int8 generated by default as identity, create_date timestamp, update_date timestamp, count_brak float8, count_products float8, count_saya float8, count_stanok float8, id_product_name int8, id_product_type int8, primary key (id));
create table tbl_product_name (id int8 generated by default as identity, create_date timestamp, update_date timestamp, product_name varchar(255) not null, primary key (id));
create table tbl_product_type (id int8 generated by default as identity, create_date timestamp, update_date timestamp, product_type varchar(255) not null, primary key (id));
alter table if exists tbl_product add constraint FKp0youvfe87h4w39ixts92cuti foreign key (id_product_name) references tbl_product_name;
alter table if exists tbl_product add constraint FKrd68se3hnfsfactdugl6bmld4 foreign key (id_product_type) references tbl_product_type;
